In [58]:
#importing modules
import numpy as np
import pandas as pd
import random

In [59]:
#importing the dataset
all_data = pd.read_csv('sobar-72.csv')
print(all_data)

    behavior_sexualRisk  behavior_eating  behavior_personalHygine  \
0                    10               13                       12   
1                    10               11                       11   
2                    10               15                        3   
3                    10               11                       10   
4                     8               11                        7   
..                  ...              ...                      ...   
67                   10               14                       14   
68                   10               12                       15   
69                   10                8                       11   
70                    9               12                       13   
71                   10               14                       14   

    intention_aggregation  intention_commitment  attitude_consistency  \
0                       4                     7                     9   
1                      10

In [60]:
#splitting the dataset into training and test datasets
train_data = all_data.head(57)
test_data = all_data.tail(15)
#print(train_data)
#print(test_data)

In [61]:
#converting to numpy arrays for ease of computation
all_arr = all_data.to_numpy()
train_arr = train_data.to_numpy()
#print(train_arr)
test_arr = test_data.to_numpy()
print(test_arr)

[[10 11  8 10 15  7  8  5 14 13  8 12  7  4  3  3  4  4  7  0]
 [10 11  9  6 15  6  8  5 14 11  8 11  7  3  2  3  3  3  3  0]
 [10 13  9 10 15  8  8  5 14  8  8 11  3  3  2  3  3  3  3  0]
 [10 12 10 10 15  6  8  5 15 11  8 13  7  3  2  3  3  3  3  0]
 [10 10 10 10 15  6  6  5 14 13  9 15  9 13  8 14 13 12 12  0]
 [10 13 11  6 15  8 10  5 15  7 10 13  7  3  5  3  3  3  3  0]
 [10 13 15 10 15  8 10  5 14  6  8 13  7  3  4  3  3  6  3  0]
 [10 15  8  6 11  6 10  5 11 15  8 15  7  3  4 11 13 10 15  0]
 [10 13 11  6 14  9 10  5 15 15 10 15  3  3  4  7  7  7 11  0]
 [10 12 13 10 11  7  7  5 14 15  9 14 10  6  6  6  9  7 11  0]
 [10 14 14 10 15  6  7  5 15 14 10 15 13  9  8 12 12 11  9  0]
 [10 12 15 10 15  8  8  5 15 14  8 12 14 11  7 13 15 11 14  0]
 [10  8 11  6 10  6  4  3 13  9  8 14 12  9  7 11 12 10 10  0]
 [ 9 12 13 10 13  6  6  5 14 13 10 13 12 11  8 12 11 13 15  0]
 [10 14 14  6 12  7  8  5 15 12 10 10 13 11  9 14 13 15 15  0]]


In [62]:
#Functions for calculating distances

#Euclidean distance
def d_euclidean(point1, point2):
    a = np.subtract(point1,point2)  
    a = np.power(a, 2)
    s = np.sum(a)
    dist = s**(1/2)
    return(dist)
    
#check = d_euclidean([2,3,4],[1,1,1])//For checking the working of the function
#check



In [63]:
#1-NN for condensing

def nrst_nbr(frame,point):
    min = None
    for row in frame:
        d = d_euclidean(row,point)
        if min is None:
            min = d
            x = row
        elif d<min:
            min = d
            x = row
    return(x)
        
#test the function
#a = np.array([[1,1,1],[0.5,0.5,0.5], [0.1,0.1,0.1],[2,2,2]])
#p = np.array([0,0,0])
#z = nrst_nbr(a,p)
#z

#Test successful!!
    

In [64]:
(r,c)=train_arr.shape
c

20

In [83]:
#Condensing the training dataset# condensed knn algorithm
S = np.array(train_arr[0] ,ndmin=2)
i = 1000
(r,c)=train_arr.shape
while(i>0):
    j = random.randint(0, 56)
    y = train_arr[j]
    a = nrst_nbr(S,y) #a contains the the row in S which is closest to the point in the training data being tested
    if a[c-1]==y[c-1]:
        #print(a)
        #print(y)
         i= i-1
    else:
        S = np.vstack((S,y) )
        i= i-1

print('final condensed set', S)
#print(S.shape)


final set [[10 13 12  4  7  9 10  1  8  7  3 14  8  5  7 12 12 11  8  1]
 [10 12 10  7 15  6  8  2  4  9  2 15 12 10  7 12 14 10 14  0]
 [10 15 13 10 15  6 10  1  7  7  2 15  7  3  4  3 11  5  9  0]
 [ 7 15  7  6 11  8  8  5  3  3  4 15  3  8  2  9  3  4  4  1]
 [10 14  8  6 15  8 10  1  3  4  2 14  8  7  2  7 13  9  6  1]
 [10 15 15  4 15  8 10  5  3  8  3 11  3  3  2  7  8  5  3  1]
 [ 9 12 14  9 15 10  9  3  6  3  2 15 15  3 10 15 11  3 11  1]
 [10 15  7  2 15  6 10  1  3  5  2  9 15 13 10 15 13 15 15  1]
 [10 11 10 10 15  7  7  1  5  4  2 15 13  7  4  4  4  4  4  1]
 [ 8 12  9 10 10  5 10  5  5  5  2 10  9 13  2  9  8  7 12  1]
 [10 10  5  2 15  8 10  5 13 15 10 15  3  3  2 13 15 15 15  0]
 [10 15  9  3 15  8 10  1  3  5  6 10 15 13 10 15 15 15 15  0]
 [10  3  5  2  9  6 10  1  3  9  6 11 10  9  9 14  6 10 10  0]
 [10 10 12  5  7  6  6  4  5 10  4 11  9 11  8 11 11 10 11  0]
 [10 12 12  8 10  8  6  2  7  6  2 12 11  9  8 12 10 10  9  1]
 [10 15 15  8  9  8  9  4  7  6  4 12 12 14  

In [ ]:
#5-KNN on the condensed data set
distances = []

for i in test_arr:
    for j in S:
        dis = d_euclidean(i,j)
        
        
        
        
    


None
